# Vertex AI CPU-Only Configuration (No GPU quota needed)

workerPoolSpecs:
  - machineSpec:
      machineType: n1-highmem-16  # 16 vCPUs, 104GB RAM
      # No accelerator - CPU only
    replicaCount: 1
    pythonPackageSpec:
      executorImageUri: us-docker.pkg.dev/vertex-ai/training/tf-cpu.2-13.py310:latest
      packageUris:
        - gs://everyday-christian-models/training/trainer.tar.gz
      pythonModule: train_vertex_ai
      args:
        - "--epochs=30"  # Reduced from 50 for CPU
        - "--batch-size=128"  # Smaller batch for CPU
        - "--learning-rate=0.001"
        - "--bucket-name=everyday-christian-models"